/** @type {import('next').NextConfig} */
const nextConfig = {
  compress: true,
  poweredByHeader: false,
  // react-markdown, remark-math, rehype-katex and their deps are ESM-only.
  // Next.js 14 (webpack) requires them listed here so they get transpiled.
  transpilePackages: [
    "react-markdown",
    "remark-math",
    "rehype-katex",
    "remark-parse",
    "remark-rehype",
    "rehype-stringify",
    "unified",
    "bail",
    "is-plain-obj",
    "trough",
    "vfile",
    "vfile-message",
    "unist-util-stringify-position",
    "mdast-util-from-markdown",
    "mdast-util-to-markdown",
    "mdast-util-math",
    "micromark",
    "micromark-util-combine-extensions",
    "micromark-util-chunked",
    "micromark-extension-math",
    "hast-util-to-jsx-runtime",
    "hast-util-from-parse5",
    "hast-util-raw",
    "hastscript",
    "property-information",
    "space-separated-tokens",
    "comma-separated-tokens",
    "web-namespaces",
    "zwitch",
    "html-void-elements",
    "trim-lines",
    "unist-util-visit",
    "unist-util-is",
    "unist-util-position",
    "mdast-util-to-hast",
    "mdast-util-definitions",
    "mdast-util-phrasing-content",
    "decode-named-character-reference",
    "character-entities",
    "ccount",
    "markdown-table",
    "longest-streak",
  ],
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**",
      },
    ],
  },
};

module.exports = nextConfig;
